name: Restx CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[maven-release-plugin]') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build and Test
        run: ./mvnw clean verify